"""initial migration

Revision ID: 1a1de0917b3a
Revises: 
Create Date: 2026-07-21 17:07:33.774239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a1de0917b3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_constraint(op.f('fk_employee_user'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('tasks_assigned_to_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_to_fkey'), 'tasks', 'users', ['assigned_to'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employee_user'), 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table('project_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_members_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_members_pkey'))
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    # ### end Alembic commands ###
