"""add_created_by_to_employee

Revision ID: 67a7145d146e
Revises: d6ab9bf85090
Create Date: 2026-07-24 14:07:39.515926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a7145d146e'
down_revision: Union[str, Sequence[str], None] = 'd6ab9bf85090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the column as nullable
    op.add_column(
        "employees",
        sa.Column("created_by", sa.Integer(), nullable=True),
    )

    # Step 2: Populate existing rows
    op.execute(
        """
        UPDATE employees
        SET created_by = user_id
        WHERE user_id IS NOT NULL
        """
    )

    # If there are employees without a user_id, use an admin user's id.
    # Replace 1 below if your admin has a different id.
    op.execute(
        """
        UPDATE employees
        SET created_by = 1
        WHERE created_by IS NULL
        """
    )

    # Step 3: Make the column NOT NULL
    op.alter_column(
        "employees",
        "created_by",
        nullable=False,
    )

    op.create_foreign_key(
        None,
        "employees",
        "users",
        ["created_by"],
        ["id"],
    )

    # Keep this only if you intentionally want to remove this unique constraint.
    # Otherwise delete this line.
    op.drop_constraint(
        op.f("uq_project_employee"),
        "project_employees",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_project_employee'), 'project_employees', ['project_id', 'employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'created_by')
    # ### end Alembic commands ###
