"""add daily worksheets

Revision ID: b7ea2b630ed5
Revises: 7735d4d29a69
Create Date: 2026-09-09 11:57:24.757169

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7ea2b630ed5'
down_revision: Union[str, Sequence[str], None] = '7735d4d29a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_worksheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_daily_worksheets_employee_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_worksheets'))
    )
    op.create_index(op.f('ix_daily_worksheets_id'), 'daily_worksheets', ['id'], unique=False)
    op.create_table('daily_worksheet_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['worksheet_id'], ['daily_worksheets.id'], name=op.f('fk_daily_worksheet_tasks_worksheet_id_daily_worksheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_worksheet_tasks'))
    )
    op.create_index(op.f('ix_daily_worksheet_tasks_id'), 'daily_worksheet_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_worksheet_tasks_id'), table_name='daily_worksheet_tasks')
    op.drop_table('daily_worksheet_tasks')
    op.drop_index(op.f('ix_daily_worksheets_id'), table_name='daily_worksheets')
    op.drop_table('daily_worksheets')
    # ### end Alembic commands ###
