"""add weekly planner

Revision ID: fa40b814df06
Revises: 2cf8c0aa57f6
Create Date: 2026-08-24 12:06:53.407341

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa40b814df06'
down_revision: Union[str, Sequence[str], None] = '2cf8c0aa57f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_planner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_weekly_planner_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_weekly_planner_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_planner'))
    )
    op.create_index(op.f('ix_weekly_planner_id'), 'weekly_planner', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_planner_week_start'), 'weekly_planner', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_planner_week_start'), table_name='weekly_planner')
    op.drop_index(op.f('ix_weekly_planner_id'), table_name='weekly_planner')
    op.drop_table('weekly_planner')
    # ### end Alembic commands ###
